FROM maven:3.9.11-eclipse-temurin-21-noble

ARG GIT_BRANCH
 
ENV DEBIAN_FRONTEND=noninteractive
 
RUN apt-get update
RUN apt-get install -y git
 
RUN mkdir /opt/app
WORKDIR /opt/app
RUN git clone https://github.com/speakly-project/bank-backend.git
WORKDIR /opt/app/bank-backend
RUN git switch -c ${GIT_BRANCH} origin/${GIT_BRANCH}
RUN mvn clean install -DskipTests
 
EXPOSE 8080
 
 
CMD ["java","-jar", "target/bank-backend-0.0.1-SNAPSHOT.jar"]