FROM node:22.19.0 AS build
 
RUN apt-get update
RUN apt-get install -y git
 
RUN mkdir /opt/app
WORKDIR /opt/app
RUN git clone https://github.com/speakly-project/bank-frontend.git
WORKDIR /opt/app/bank-frontend
RUN git switch -c develop origin/develop
RUN npm ci
RUN npm run build --prod
 
 
 
FROM nginx:1.28.0-alpine3.21
COPY --from=build /opt/app/bank-frontend/dist/speakly-adm-frontend/browser/ /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]