FROM node:22.19.0 AS build

ARG GIT_BRANCH
ARG API_URL

RUN apt-get update
RUN apt-get install -y git
 
RUN mkdir /opt/app
WORKDIR /opt/app
RUN git clone https://github.com/speakly-project/store-client-frontend.git
WORKDIR /opt/app/store-client-frontend
RUN git switch -c ${GIT_BRANCH} origin/${GIT_BRANCH}

RUN npm ci
# Reemplazar la URL antes del build
RUN sed -i "s|API_URL_PLACEHOLDER|${API_URL}|" src/environments/environment.ts


RUN npm run build --prod
 
 
 
FROM nginx:1.28.0-alpine3.21
COPY --from=build /opt/app/store-client-frontend/dist/store-frontend/browser/ /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]